// Search
export const SET_SEARCHED_QUERY = 'SET_SEARCHED_QUERY';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const ADD_SEARCHED_MOVIES = 'ADD_SEARCHED_MOVIES';
export const RESET_SEARCHED_MOVIES = 'RESET_SEARCHED_MOVIES';
export const SET_SEARCHED_MOVIES_COUNT = 'SET_SEARCHED_MOVIES_COUNT';
export const SET_SEARCHED_MOVIE_DETAIL = 'SET_SEARCHED_MOVIE_DETAIL';

// User
export const SET_USERS_FAVORITE_MOVIE_IDS = 'SET_USERS_FAVORITE_MOVIE_IDS';
export const ADD_MOVIE_TO_FAVORITES = 'ADD_MOVIE_TO_FAVORITES';
export const REMOVE_MOVIE_FROM_FAVORITES = 'REMOVE_MOVIE_FROM_FAVORITES';